// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_3_Week_11_DB_API.Models
{
    public partial class Class
    {
        public Class()
        {
            FacultyClasses = new HashSet<FacultyClass>();
            StudentSchedules = new HashSet<StudentSchedule>();
            Subjects = new HashSet<Subject>();
        }

        public string ClassId { get; set; }
        public string SubjectId { get; set; }
        public int? Credits { get; set; }
        public string ClassRoomNumber { get; set; }
        public DateTime? StartDate { get; set; }

        public virtual Subject Subject { get; set; }
        public virtual ICollection<FacultyClass> FacultyClasses { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}