// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_3_Week_11_DB_API.Models
{
    public partial class Faculty
    {
        public Faculty()
        {
            FacultyClasses = new HashSet<FacultyClass>();
        }

        public string FacultyId { get; set; }
        public string Title { get; set; }
        public bool? TenureIsChecked { get; set; }
        public string FacFirstName { get; set; }
        public string FacLastName { get; set; }

        public virtual ICollection<FacultyClass> FacultyClasses { get; set; }
    }
}